references:
  - J.G. Hust and A.B. Lankford,
    Thermal Conductivity of Aluminum, Copper, Iron, and Tungsten from 1K to the Melting Point,
    US Department of Commerce, Boulder, Colorado, 1984,
    fit to Tab. 4.4.1 (RRR=300, T_min=150K, T_max=1000K)
  - https://www.engineeringtoolbox.com/specific-heat-metals-d_152.html

output: [T]

K_11: 8.034e+1
K_11,T: -1.216e-1
K_11,T^2: 1.327e-4
K_11,T^3: -7.993e-8

T_ref: 293.15

C_p: 450.0
