type: Hooke

references:
  - S.A. Kim and W.L. Johnson,
    Materials Science & Engineering A 452-453:633-639, 2007,
    https://doi.org/10.1016/j.msea.2006.11.147,
    Tab. 1 (averaged for bcc)

C_11: 267.9e+9
C_12: 110.8e+9
C_44: 78.9e+9
