type: phenopowerlaw

references:
  - T. Takeuchi,
    Transactions of the Japan Institute of Metals 16(10):629-640, 1975,
    https://doi.org/10.2320/matertrans1960.16.629,
    fitted to Fig. 3b ([111] and [001])

output: [xi_sl, gamma_sl]

N_sl: [12]

dot_gamma_0_sl: [3.e-3]
n_sl: [20]
a_sl: [0.6]
xi_0_sl: [1.6e+6]
xi_inf_sl: [96.4e+6]
h_0_sl-sl: [0.35e+9]
h_sl-sl: [1, 1, 5.123, 0.574, 1.123, 1.123, 1]
