type: phenopowerlaw

references:
  - W.F. Hosford et al.,
    Acta Metallurgica 8(3):187-199, 1960,
    https://doi.org/10.1016/0001-6160(60)90127-9,
    fitted to Fig. 5 ([111] and [001])

output: [xi_sl, gamma_sl]

N_sl: [12]

dot_gamma_0_sl: [7.5e-5]
n_sl: [20]
a_sl: [5.4]
xi_0_sl: [2.69e+6]
xi_inf_sl: [67.5e+6]
h_0_sl-sl: [0.2815e+9]
h_sl-sl: [1, 1, 5.123, 0.574, 1.123, 1.123, 1]
